# Generated by Django 4.0.4 on 2022-06-07 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='paymentDate',
            field=models.DateField(auto_now=True),
        ),
    ]
