# Generated by Django 4.0.4 on 2022-05-11 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_email', models.EmailField(max_length=300)),
                ('default_postcode', models.CharField(blank=True, max_length=20)),
                ('default_town', models.CharField(blank=True, max_length=40)),
                ('default_address_1', models.CharField(blank=True, max_length=100)),
                ('default_address_2', models.CharField(blank=True, max_length=100)),
                ('default_country', models.CharField(blank=True, max_length=80)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
