# Generated by Django 4.0.4 on 2022-04-22 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursereview',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='coursereview',
            old_name='user_id',
            new_name='user',
        ),
    ]
