# Generated by Django 4.0.4 on 2022-05-10 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_category_course_created_at_course_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='category_id',
            new_name='category',
        ),
    ]
