# Generated by Django 4.0.4 on 2022-06-17 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='blogImage',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
