# Generated by Django 4.0.4 on 2022-04-29 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=50)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=300)),
                ('address_line_1', models.CharField(max_length=100)),
                ('address_line_2', models.CharField(max_length=100)),
                ('town_or_city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=100)),
                ('postCode', models.CharField(max_length=10)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('order_cost', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('order_tax', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('order_total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('original_cart', models.TextField(default='')),
                ('stripe_payment_id', models.CharField(default='', max_length=300)),
            ],
        ),
    ]
