# Generated by Django 4.0.4 on 2022-04-29 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogimage',
            name='blog_post_id',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='author',
        ),
        migrations.DeleteModel(
            name='BlogComment',
        ),
        migrations.DeleteModel(
            name='BlogImage',
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
